MACRO(SETUP_PLUGIN PLUGIN_NAME)

    SET(TARGET_NAME ${PLUGIN_NAME} )
	
	IF (WIN32)
	  ADD_DEFINITIONS(-DNOMINMAX)
	ENDIF (WIN32)

	INCLUDE_DIRECTORIES( 
	  ${CMAKE_CURRENT_SOURCE_DIR}/../../include/
	  ${OSG_INCLUDE_DIR}
	)

  ADD_LIBRARY(${TARGET_NAME} ${DTENTITY_PLUGINS_DYNAMIC_OR_STATIC}
		${TARGET_H}
		${TARGET_SRC}
	)

  TARGET_LINK_LIBRARIES(${TARGET_NAME} ${TARGET_ADDED_LIBRARIES} ${TARGET_COMMON_LIBRARIES})
	
  INCLUDE(PluginInstall OPTIONAL)

  SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
  
  IF (MSVC)    
    SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES PREFIX "../../plugins/")
    SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES IMPORT_PREFIX "../")
  ENDIF (MSVC) 

ENDMACRO(SETUP_PLUGIN)
