# - Find Delta3D
#   Find Delta3D includes and library
#

IF(DELTA3D_INCLUDE_DIR AND DELTA3D_LIBRARIES)

  # in cache already
  SET(DELTA3D_FOUND TRUE)

ELSE(DELTA3D_INCLUDE_DIR AND DELTA3D_LIBRARIES)
   file(TO_CMAKE_PATH "$ENV{VIEWER_EXT_DEP}" EXTDEPPATH)
   
  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_PATH(DELTA3D_INCLUDE_DIR dtCore/camera.h PATHS ${EXTDEPPATH}/include)
  
  FIND_LIBRARY_WITH_DEBUG(DTABC_LIBRARIES dtABC ${EXTDEPPATH}/lib)
  FIND_LIBRARY_WITH_DEBUG(DTANIM_LIBRARIES dtAnim ${EXTDEPPATH}/lib)
  FIND_LIBRARY_WITH_DEBUG(DTAI_LIBRARIES dtAI ${EXTDEPPATH}/lib)
  FIND_LIBRARY_WITH_DEBUG(DTCORE_LIBRARIES dtCore ${EXTDEPPATH}/lib)
  FIND_LIBRARY_WITH_DEBUG(DTUTIL_LIBRARIES dtUtil ${EXTDEPPATH}/lib)
  FIND_LIBRARY_WITH_DEBUG(DTINPUTPLIB_LIBRARIES dtInputPLib ${EXTDEPPATH}/lib)
    
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(DTABC_LIBRARIES DEFAULT_MSG DTABC_LIBRARIES DELTA3D_INCLUDE_DIR)

ENDIF(DELTA3D_INCLUDE_DIR AND DELTA3D_LIBRARIES)

