# - Find V8
#   Find V8 includes and library
#

IF(V8_INCLUDE_DIR AND V8_LIBRARIES)

  # in cache already
  SET(V8_FOUND TRUE)

ELSE(V8_INCLUDE_DIR AND V8_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  set(V8_INC_PATHS
		   /usr/include
		   ${CMAKE_INCLUDE_PATH}
  )
  FIND_PATH(V8_INCLUDE_DIR v8.h PATHS ${V8_INC_PATHS})

  FIND_LIBRARY_WITH_DEBUG(V8_LIBRARIES v8 "")
  
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(V8 DEFAULT_MSG V8_LIBRARIES V8_INCLUDE_DIR)

ENDIF(V8_INCLUDE_DIR AND V8_LIBRARIES)

