IF(AMOP_INCLUDE_DIR AND AMOP_LIBRARY)

  # in cache already
  SET(AMOP_FOUND TRUE)

ELSE(AMOP_INCLUDE_DIR AND AMOP_LIBRARY)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)
  
  FIND_PATH(AMOP_INCLUDE_DIR MockObject.h PATHS $ENV{VIEWER_EXT_DEP}/include/amop)
  FIND_LIBRARY_WITH_DEBUG(AMOP_LIBRARY amop $ENV{VIEWER_EXT_DEP}/lib)

ENDIF(AMOP_INCLUDE_DIR AND AMOP_LIBRARY)
