# - Find OpenThreads
#   Find OpenThreads includes and library
#

IF(OPENTHREADS_INCLUDE_DIR AND OPENTHREADS_LIBRARIES)

  # in cache already
  SET(OPENTHREADS_FOUND TRUE)

ELSE(OPENTHREADS_INCLUDE_DIR AND OPENTHREADS_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_PATH(OPENTHREADS_INCLUDE_DIR OpenThreads/ScopedLock PATHS
      ${CMAKE_INCLUDE_PATH}
      ${OSG_ROOT_DIR}/include
   )

  
  FIND_LIBRARY_WITH_DEBUG(OPENTHREADS_LIBRARIES OpenThreads "")
  IF(NOT OPENTHREADS_LIBRARIES)
    FIND_LIBRARY_WITH_DEBUG(OPENTHREADS_LIBRARIES OpenThreads "")
  ENDIF(NOT OPENTHREADS_LIBRARIES)
  
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENTHREADS DEFAULT_MSG OPENTHREADS_LIBRARIES OPENTHREADS_INCLUDE_DIR)

  SET(OPENTHREADS_INCLUDE_DIR ${OPENTHREADS_INCLUDE_DIR} ${OSG_BUILD_DIR}/include)
  message (STATUS "Added build-specific include dir for OpenThreads...")

ENDIF(OPENTHREADS_INCLUDE_DIR AND OPENTHREADS_LIBRARIES)
