# - Find Delta3D
#   Find Delta3D includes and library
#

IF(DELTA3D_INCLUDE_DIR AND DELTA3D_LIBRARIES)

  # in cache already
  SET(DELTA3D_FOUND TRUE)

ELSE(DELTA3D_INCLUDE_DIR AND DELTA3D_LIBRARIES)
   
  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_PATH(DELTA3D_INCLUDE_DIR dtCore/camera.h PATHS ${CMAKE_INCLUDE_PATH})
  
  FIND_LIBRARY_WITH_DEBUG(DTABC_LIBRARIES dtABC "")
  FIND_LIBRARY_WITH_DEBUG(DTANIM_LIBRARIES dtAnim "")
  FIND_LIBRARY_WITH_DEBUG(DTAI_LIBRARIES dtAI "")
  FIND_LIBRARY_WITH_DEBUG(DTCORE_LIBRARIES dtCore "")
  FIND_LIBRARY_WITH_DEBUG(DTUTIL_LIBRARIES dtUtil "")
  FIND_LIBRARY_WITH_DEBUG(DTINPUTPLIB_LIBRARIES dtInputPLib "")
    
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(DTABC_LIBRARIES DEFAULT_MSG DTABC_LIBRARIES DELTA3D_INCLUDE_DIR)

ENDIF(DELTA3D_INCLUDE_DIR AND DELTA3D_LIBRARIES)

