IF(OSGEPHEMERIS_INCLUDE_DIR AND OSGEPHEMERIS_LIBRARIES)

  # in cache already
  SET(OSGEPHEMERIS_FOUND TRUE)

ELSE(OSGEPHEMERIS_INCLUDE_DIR AND OSGEPHEMERIS_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  set(OSGEPHEMERIS_INC_PATHS
    /usr/include
    /usr/local
    /usr
	${CMAKE_INCLUDE_PATH}
  )
  FIND_PATH(OSGEPHEMERIS_INCLUDE_DIR osgEphemeris/EphemerisModel.h PATHS ${OSGEPHEMERIS_INC_PATHS})

  FIND_LIBRARY_WITH_DEBUG(OSGEPHEMERIS_LIBRARIES osgEphemeris "")  
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSGEPHEMERIS DEFAULT_MSG OSGEPHEMERIS_LIBRARIES OSGEPHEMERIS_INCLUDE_DIR)

ENDIF(OSGEPHEMERIS_INCLUDE_DIR AND OSGEPHEMERIS_LIBRARIES)

