IF(XERCES_INCLUDE_DIR AND XERCES_LIBRARIES)

  # in cache already
  SET(XERCES_FOUND TRUE)

ELSE(XERCES_INCLUDE_DIR AND XERCES_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_LIBRARY_WITH_DEBUG(XERCES_LIBRARIES XercesBase "")
  FIND_PATH(XERCES_INCLUDE_DIR xercesc/sax/Parser.hpp PATH_SUFFIXES xerces)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(XERCES DEFAULT_MSG XERCES_LIBRARIES XERCES_INCLUDE_DIR)

ENDIF(XERCES_INCLUDE_DIR AND XERCES_LIBRARIES)
