IF(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)

  SET(LIBROCKET_FOUND TRUE)

ELSE(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  SET(ROCKET_FIND_PATHS 
	$ENV{VIEWER_EXT_DEP}/include
	${EXTDEPPATH}/include
	$ENV{VIEWER_EXT_DEP}/lib
	${EXTDEPPATH}/lib
  )
  FIND_PATH(LIBROCKET_INCLUDE_DIR Rocket/Core.h PATHS ${ROCKET_FIND_PATHS})

  FIND_LIBRARY_WITH_DEBUG(LIBROCKET_CORE_LIBRARY RocketCore "${ROCKET_FIND_PATHS}")
  FIND_LIBRARY_WITH_DEBUG(LIBROCKET_CONTROLS_LIBRARY RocketControls "${ROCKET_FIND_PATHS}")
  FIND_LIBRARY_WITH_DEBUG(LIBROCKET_DEBUGGER_LIBRARY RocketDebugger "${ROCKET_FIND_PATHS}")

ENDIF(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)
