IF(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)

  SET(LIBROCKET_FOUND TRUE)

ELSE(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_PATH(LIBROCKET_INCLUDE_DIR Rocket/Core.h PATHS ${EXTDEPPATH}/include)

  FIND_LIBRARY_WITH_DEBUG(LIBROCKET_CORE_LIBRARY RocketCore "lib lib64")
  FIND_LIBRARY_WITH_DEBUG(LIBROCKET_CONTROLS_LIBRARY RocketControls "lib lib64")
  FIND_LIBRARY_WITH_DEBUG(LIBROCKET_DEBUGGER_LIBRARY RocketDebugger "lib lib64")

ENDIF(LIBROCKET_INCLUDE_DIR AND LIBROCKET_LIBRARIES)
