IF(PROTOBUF_INCLUDE_DIR AND PROTOBUF_LIBRARIES)

  SET(PROTOBUF_FOUND TRUE)

ELSE(PROTOBUF_INCLUDE_DIR AND PROTOBUF_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  set(PROTOBUF_INC_PATHS
    /usr/include
    /usr/local
    /usr
	${CMAKE_INCLUDE_PATH}
  )
  FIND_PATH(PROTOBUF_INCLUDE_DIR google/protobuf/stubs/common.h PATHS ${PROTOBUF_INC_PATHS})
  FIND_LIBRARY_WITH_DEBUG(PROTOBUF_LIBRARIES protobuf "")
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PROTOBUF DEFAULT_MSG PROTOBUF_LIBRARIES PROTOBUF_INCLUDE_DIR)

ENDIF(PROTOBUF_INCLUDE_DIR AND PROTOBUF_LIBRARIES)

