MACRO(SETUP_PLUGIN PLUGIN_NAME)

    SET(TARGET_NAME ${PLUGIN_NAME} )

    #MESSAGE("in -->SETUP_PLUGIN<-- ${TARGET_NAME}-->${TARGET_SRC} <--> ${TARGET_H}<--")

    ## we have set up the target label and targetname by taking into account global prfix (osgdb_)
	
	IF (WIN32)
	  ADD_DEFINITIONS(-DNOMINMAX)
	ENDIF (WIN32)

	INCLUDE_DIRECTORIES( 
	  ${CMAKE_CURRENT_SOURCE_DIR}/../../include/
	  ${OSG_INCLUDE_DIRS}
	)

	ADD_LIBRARY(${TARGET_NAME} ${DTENTITY_USER_DEFINED_DYNAMIC_OR_STATIC}
		${TARGET_H}
		${TARGET_SRC}
	)

	TARGET_LINK_LIBRARIES(${TARGET_NAME} ${TARGET_ADDED_LIBRARIES} ${TARGET_COMMON_LIBRARIES})
	
  INCLUDE(PluginInstall OPTIONAL)

  SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")


ENDMACRO(SETUP_PLUGIN)
