# - Find OpenThreads
#   Find OpenThreads includes and library
#

IF(OPENTHREADS_INCLUDE_DIR AND OPENTHREADS_LIBRARIES)

  # in cache already
  SET(OPENTHREADS_FOUND TRUE)

ELSE(OPENTHREADS_INCLUDE_DIR AND OPENTHREADS_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_PATH(OPENTHREADS_INCLUDE_DIR OpenThreads/ScopedLock PATHS $ENV{VIEWER_EXT_DEP}/include)
  
  FIND_LIBRARY_WITH_DEBUG(OPENTHREADS_LIBRARIES OpenThreads $ENV{VIEWER_EXT_DEP}/lib)
  IF(NOT OPENTHREADS_LIBRARIES)
    FIND_LIBRARY_WITH_DEBUG(OPENTHREADS_LIBRARIES OpenThreads $ENV{VIEWER_EXT_DEP}/lib)
  ENDIF(NOT OPENTHREADS_LIBRARIES)
  
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENTHREADS DEFAULT_MSG OPENTHREADS_LIBRARIES OPENTHREADS_INCLUDE_DIR)

ENDIF(OPENTHREADS_INCLUDE_DIR AND OPENTHREADS_LIBRARIES)

