IF(ENET_INCLUDE_DIR AND ENET_LIBRARIES)

  # in cache already
  SET(ENET_FOUND TRUE)

ELSE(ENET_INCLUDE_DIR AND ENET_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  FIND_LIBRARY_WITH_DEBUG(ENET_LIBRARIES ENETBase "")
  FIND_PATH(ENET_INCLUDE_DIR enet.h PATH_SUFFIXES enet)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(ENET DEFAULT_MSG ENET_LIBRARIES ENET_INCLUDE_DIR)

ENDIF(ENET_INCLUDE_DIR AND ENET_LIBRARIES)
