# - Find OPENAL
#   Find OPENAL includes and library
#

IF(OPENAL_INCLUDE_DIR AND OPENAL_LIBRARIES)

  # in cache already
  SET(OPENAL_FOUND TRUE)

ELSE(OPENAL_INCLUDE_DIR AND OPENAL_LIBRARIES)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)

  set(OPENAL_INC_PATHS $ENV{VIEWER_EXT_DEP}/include
    $ENV{VIEWER_EXT_DEP}/include/AL
	/usr/include
    /usr/include/AL
    /usr/local
    /usr
  )
  FIND_PATH(OPENAL_INCLUDE_DIR al.h PATHS ${OPENAL_INC_PATHS})

  #look for the OpenAL32 library
#  FIND_LIBRARY(OPENAL_LIBRARIES NAMES OpenAL32 PATHS $ENV{VIEWER_EXT_DEP}/lib)
  FIND_LIBRARY_WITH_DEBUG(OPENAL_LIBRARIES openal $ENV{VIEWER_EXT_DEP}/lib)
  FIND_LIBRARY_WITH_DEBUG(OPENAL_LIBRARIES OpenAL32-Soft $ENV{VIEWER_EXT_DEP}/lib)
  # look for the alut libraries
  FIND_LIBRARY_WITH_DEBUG(OPENAL_UTIL_LIBRARIES alut $ENV{VIEWER_EXT_DEP}/lib)
  FIND_LIBRARY_WITH_DEBUG(OPENAL_UTIL_LIBRARIES alut-soft $ENV{VIEWER_EXT_DEP}/lib)
  
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENAL DEFAULT_MSG OPENAL_LIBRARIES OPENAL_INCLUDE_DIR)

ENDIF(OPENAL_INCLUDE_DIR AND OPENAL_LIBRARIES)

