IF(AMOP_INCLUDE_DIR AND AMOP_LIBRARY)

  # in cache already
  SET(AMOP_FOUND TRUE)

ELSE(AMOP_INCLUDE_DIR AND AMOP_LIBRARY)

  INCLUDE(FindPackageHandleStandardArgs)
  INCLUDE(FindLibraryWithDebug)
  
  FIND_PATH(AMOP_INCLUDE_DIR MockObject.h PATHS ${CMAKE_INCLUDE_PATH}/amop)
  FIND_LIBRARY_WITH_DEBUG(AMOP_LIBRARY amop "")

ENDIF(AMOP_INCLUDE_DIR AND AMOP_LIBRARY)
